### ISSUE TITLE
Access denied on link

### ISSUE THREAD

**Issue by jsltran3** [learn-co-curriculum/phase-3-quiz-object-orientation-fundamentals#1]
### Canvas Link

https://learning.flatironschool.com/courses/5931/quizzes/31591

### Concern

Object-Orientation Fundamentals Quiz

For the question:
class Pet
  def initialize(name)
    @name = name
  end

  def name=(name)
    @name = name
  end

  def name
    @name
  end
end

dog = Pet.new
Pet.new in this example will instantiate a new instance of the Pet class.

There's a link for one of the old articles but there's denied access:

Source/s:

[Object Initialization](https://learning.flatironschool.com/courses/5931/pages/object-initialization)

### Additional Context

Error: Access Denied
You don't have access to view this resource.

Have specific feedback?
[Tell us here!Links to an external site.](https://flatironschoolforms.formstack.com/forms/canvas_feedback?CourseID=5931&LessonID=object-initialization&LessonType=pages&CanvasUserID=8450&Course=None)

### Suggested Changes

Replace link please

**Comment by lizbur10** [comment]
Hi @jsltran3 ! I'm sorry to hear that you ran into this problem! I'm not able to recreate it - when I check the quiz, the links are working for me. Are you still having the issue? If so, I recommend that you use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.

Also, FYI, those source links just link to the lesson that explains the concept covered by the question, so you can also navigate directly to the Object Initialization lesson, which appears a bit earlier in the module.

Good luck and thanks for contributing to the Flatiron School curriculum 💙
